spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library_manager_web
    username: root
    password: Qxy000309
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: edu.xtu.library.entity